[project]
name = "tp-coo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cmake>=4.1.0",
    "django>=5.2.6",
    "meson>=1.9.1",
]

[dependency-groups]
dev = [
    "ipython>=9.5.0",
    "pre-commit>=4.3.0",
]
